ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE users
SET role = 'USER'
WHERE role IS NULL;

UPDATE users
SET active = TRUE
WHERE active IS NULL;

